-- ~/.config/nvim/ftplugin/scheme.lua

-- Define o programa de keyword (opcional, mas boa prática)
-- vim.bo.keywordprg = ":!chicken-doc"

-- Cria um autocomando que roda SEMPRE que um LSP conecta neste buffer
-- vim.api.nvim_create_autocmd("LspAttach", {
--   buffer = 0, -- Apenas para o buffer atual
--   callback = function(args)
--     local client = vim.lsp.get_client_by_id(args.data.client_id)
--
--     -- Se for o chicken_lsp, nós forçamos a tecla K
--     if client and client.name == "chicken_lsp" then
--       vim.keymap.set("n", "K", function()
--         local word = vim.fn.expand("<cword>")
--         -- Executa o comando no terminal
--         vim.cmd("!chicken-doc " .. word)
--       end, { buffer = args.buf, desc = "Chicken Doc (Force)" })
--     end
--   end,
-- })
